version: '3.4'
services:
  database:
    image: tenforce/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
    ports:
      - "8890:8890"
  converter:
    build: ./converter
    environment:
      ENDPOINT: 'http://database:8890/sparql'
      KANDIDATENLIJST_TYPE_IRI: 'http://data.vlaanderen.be/id/concept/KandidatenlijstLijsttype/90e3b7d0-2fae-43a1-957e-6daa8d072be1' # provincieraad
      BESTUURSORGAAN_TYPE_IRI: 'http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e00000c' # provincieraad
      ORGAAN_START_DATUM: '2019-01-01'
      LOG_LEVEL: 'info'
    volumes:
      - './data/input-provincies:/data/input'
      - './data/output:/data/output'
      - './data/transforms:/data/transforms'
